// Generated by gencpp from file ngimu/NGIMUQuaternion.msg
// DO NOT EDIT!


#ifndef NGIMU_MESSAGE_NGIMUQUATERNION_H
#define NGIMU_MESSAGE_NGIMUQUATERNION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ngimu
{
template <class ContainerAllocator>
struct NGIMUQuaternion_
{
  typedef NGIMUQuaternion_<ContainerAllocator> Type;

  NGIMUQuaternion_()
    : header()
    , w(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  NGIMUQuaternion_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , w(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _w_type;
  _w_type w;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::ngimu::NGIMUQuaternion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ngimu::NGIMUQuaternion_<ContainerAllocator> const> ConstPtr;

}; // struct NGIMUQuaternion_

typedef ::ngimu::NGIMUQuaternion_<std::allocator<void> > NGIMUQuaternion;

typedef boost::shared_ptr< ::ngimu::NGIMUQuaternion > NGIMUQuaternionPtr;
typedef boost::shared_ptr< ::ngimu::NGIMUQuaternion const> NGIMUQuaternionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ngimu::NGIMUQuaternion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ngimu::NGIMUQuaternion_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ngimu

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'ngimu': ['/home/awad1080/Desktop/ngimu_ws/src/ngimu/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ngimu::NGIMUQuaternion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ngimu::NGIMUQuaternion_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ngimu::NGIMUQuaternion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ngimu::NGIMUQuaternion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ngimu::NGIMUQuaternion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ngimu::NGIMUQuaternion_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ngimu::NGIMUQuaternion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ac652aa6e3bc77b5484994b52f2adf1";
  }

  static const char* value(const ::ngimu::NGIMUQuaternion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ac652aa6e3bc77bULL;
  static const uint64_t static_value2 = 0x5484994b52f2adf1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ngimu::NGIMUQuaternion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ngimu/NGIMUQuaternion";
  }

  static const char* value(const ::ngimu::NGIMUQuaternion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ngimu::NGIMUQuaternion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 w\n\
float32 x\n\
float32 y \n\
float32 z\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::ngimu::NGIMUQuaternion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ngimu::NGIMUQuaternion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.w);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NGIMUQuaternion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ngimu::NGIMUQuaternion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ngimu::NGIMUQuaternion_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NGIMU_MESSAGE_NGIMUQUATERNION_H
