// Generated by gencpp from file ngimu/NGIMURotationMatrix.msg
// DO NOT EDIT!


#ifndef NGIMU_MESSAGE_NGIMUROTATIONMATRIX_H
#define NGIMU_MESSAGE_NGIMUROTATIONMATRIX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ngimu
{
template <class ContainerAllocator>
struct NGIMURotationMatrix_
{
  typedef NGIMURotationMatrix_<ContainerAllocator> Type;

  NGIMURotationMatrix_()
    : header()
    , xx(0.0)
    , xy(0.0)
    , xz(0.0)
    , yx(0.0)
    , yy(0.0)
    , yz(0.0)
    , zx(0.0)
    , zy(0.0)
    , zz(0.0)  {
    }
  NGIMURotationMatrix_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , xx(0.0)
    , xy(0.0)
    , xz(0.0)
    , yx(0.0)
    , yy(0.0)
    , yz(0.0)
    , zx(0.0)
    , zy(0.0)
    , zz(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _xx_type;
  _xx_type xx;

   typedef float _xy_type;
  _xy_type xy;

   typedef float _xz_type;
  _xz_type xz;

   typedef float _yx_type;
  _yx_type yx;

   typedef float _yy_type;
  _yy_type yy;

   typedef float _yz_type;
  _yz_type yz;

   typedef float _zx_type;
  _zx_type zx;

   typedef float _zy_type;
  _zy_type zy;

   typedef float _zz_type;
  _zz_type zz;





  typedef boost::shared_ptr< ::ngimu::NGIMURotationMatrix_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ngimu::NGIMURotationMatrix_<ContainerAllocator> const> ConstPtr;

}; // struct NGIMURotationMatrix_

typedef ::ngimu::NGIMURotationMatrix_<std::allocator<void> > NGIMURotationMatrix;

typedef boost::shared_ptr< ::ngimu::NGIMURotationMatrix > NGIMURotationMatrixPtr;
typedef boost::shared_ptr< ::ngimu::NGIMURotationMatrix const> NGIMURotationMatrixConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ngimu::NGIMURotationMatrix_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ngimu::NGIMURotationMatrix_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ngimu

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'ngimu': ['/home/awad1080/Desktop/ngimu_ws/src/ngimu/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ngimu::NGIMURotationMatrix_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ngimu::NGIMURotationMatrix_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ngimu::NGIMURotationMatrix_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ngimu::NGIMURotationMatrix_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ngimu::NGIMURotationMatrix_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ngimu::NGIMURotationMatrix_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ngimu::NGIMURotationMatrix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b3a9a788418885a37b0855fd9c38d8b";
  }

  static const char* value(const ::ngimu::NGIMURotationMatrix_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b3a9a788418885aULL;
  static const uint64_t static_value2 = 0x37b0855fd9c38d8bULL;
};

template<class ContainerAllocator>
struct DataType< ::ngimu::NGIMURotationMatrix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ngimu/NGIMURotationMatrix";
  }

  static const char* value(const ::ngimu::NGIMURotationMatrix_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ngimu::NGIMURotationMatrix_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 xx\n\
float32 xy\n\
float32 xz\n\
float32 yx\n\
float32 yy\n\
float32 yz\n\
float32 zx\n\
float32 zy\n\
float32 zz\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::ngimu::NGIMURotationMatrix_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ngimu::NGIMURotationMatrix_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.xx);
      stream.next(m.xy);
      stream.next(m.xz);
      stream.next(m.yx);
      stream.next(m.yy);
      stream.next(m.yz);
      stream.next(m.zx);
      stream.next(m.zy);
      stream.next(m.zz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NGIMURotationMatrix_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ngimu::NGIMURotationMatrix_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ngimu::NGIMURotationMatrix_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "xx: ";
    Printer<float>::stream(s, indent + "  ", v.xx);
    s << indent << "xy: ";
    Printer<float>::stream(s, indent + "  ", v.xy);
    s << indent << "xz: ";
    Printer<float>::stream(s, indent + "  ", v.xz);
    s << indent << "yx: ";
    Printer<float>::stream(s, indent + "  ", v.yx);
    s << indent << "yy: ";
    Printer<float>::stream(s, indent + "  ", v.yy);
    s << indent << "yz: ";
    Printer<float>::stream(s, indent + "  ", v.yz);
    s << indent << "zx: ";
    Printer<float>::stream(s, indent + "  ", v.zx);
    s << indent << "zy: ";
    Printer<float>::stream(s, indent + "  ", v.zy);
    s << indent << "zz: ";
    Printer<float>::stream(s, indent + "  ", v.zz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NGIMU_MESSAGE_NGIMUROTATIONMATRIX_H
