// Generated by gencpp from file ngimu/NGIMUBattery.msg
// DO NOT EDIT!


#ifndef NGIMU_MESSAGE_NGIMUBATTERY_H
#define NGIMU_MESSAGE_NGIMUBATTERY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ngimu
{
template <class ContainerAllocator>
struct NGIMUBattery_
{
  typedef NGIMUBattery_<ContainerAllocator> Type;

  NGIMUBattery_()
    : header()
    , batterylevel(0.0)
    , timetoempty(0.0)
    , voltage(0.0)
    , current(0.0)
    , state(0)  {
    }
  NGIMUBattery_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , batterylevel(0.0)
    , timetoempty(0.0)
    , voltage(0.0)
    , current(0.0)
    , state(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _batterylevel_type;
  _batterylevel_type batterylevel;

   typedef float _timetoempty_type;
  _timetoempty_type timetoempty;

   typedef float _voltage_type;
  _voltage_type voltage;

   typedef float _current_type;
  _current_type current;

   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::ngimu::NGIMUBattery_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ngimu::NGIMUBattery_<ContainerAllocator> const> ConstPtr;

}; // struct NGIMUBattery_

typedef ::ngimu::NGIMUBattery_<std::allocator<void> > NGIMUBattery;

typedef boost::shared_ptr< ::ngimu::NGIMUBattery > NGIMUBatteryPtr;
typedef boost::shared_ptr< ::ngimu::NGIMUBattery const> NGIMUBatteryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ngimu::NGIMUBattery_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ngimu::NGIMUBattery_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ngimu

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'ngimu': ['/home/awad1080/Desktop/ngimu_ws/src/ngimu/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ngimu::NGIMUBattery_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ngimu::NGIMUBattery_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ngimu::NGIMUBattery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ngimu::NGIMUBattery_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ngimu::NGIMUBattery_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ngimu::NGIMUBattery_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ngimu::NGIMUBattery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "63290f8e8f182b4ff13b69cfdd440f29";
  }

  static const char* value(const ::ngimu::NGIMUBattery_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x63290f8e8f182b4fULL;
  static const uint64_t static_value2 = 0xf13b69cfdd440f29ULL;
};

template<class ContainerAllocator>
struct DataType< ::ngimu::NGIMUBattery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ngimu/NGIMUBattery";
  }

  static const char* value(const ::ngimu::NGIMUBattery_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ngimu::NGIMUBattery_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 batterylevel\n\
float32 timetoempty\n\
float32 voltage\n\
float32 current\n\
char state\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::ngimu::NGIMUBattery_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ngimu::NGIMUBattery_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.batterylevel);
      stream.next(m.timetoempty);
      stream.next(m.voltage);
      stream.next(m.current);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NGIMUBattery_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ngimu::NGIMUBattery_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ngimu::NGIMUBattery_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "batterylevel: ";
    Printer<float>::stream(s, indent + "  ", v.batterylevel);
    s << indent << "timetoempty: ";
    Printer<float>::stream(s, indent + "  ", v.timetoempty);
    s << indent << "voltage: ";
    Printer<float>::stream(s, indent + "  ", v.voltage);
    s << indent << "current: ";
    Printer<float>::stream(s, indent + "  ", v.current);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NGIMU_MESSAGE_NGIMUBATTERY_H
