// Generated by gencpp from file ngimu/NGIMUMagnitudes.msg
// DO NOT EDIT!


#ifndef NGIMU_MESSAGE_NGIMUMAGNITUDES_H
#define NGIMU_MESSAGE_NGIMUMAGNITUDES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ngimu
{
template <class ContainerAllocator>
struct NGIMUMagnitudes_
{
  typedef NGIMUMagnitudes_<ContainerAllocator> Type;

  NGIMUMagnitudes_()
    : header()
    , mag_gyroscope(0.0)
    , mag_accelerometer(0.0)
    , mag_magnetometer(0.0)  {
    }
  NGIMUMagnitudes_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mag_gyroscope(0.0)
    , mag_accelerometer(0.0)
    , mag_magnetometer(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _mag_gyroscope_type;
  _mag_gyroscope_type mag_gyroscope;

   typedef float _mag_accelerometer_type;
  _mag_accelerometer_type mag_accelerometer;

   typedef float _mag_magnetometer_type;
  _mag_magnetometer_type mag_magnetometer;





  typedef boost::shared_ptr< ::ngimu::NGIMUMagnitudes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ngimu::NGIMUMagnitudes_<ContainerAllocator> const> ConstPtr;

}; // struct NGIMUMagnitudes_

typedef ::ngimu::NGIMUMagnitudes_<std::allocator<void> > NGIMUMagnitudes;

typedef boost::shared_ptr< ::ngimu::NGIMUMagnitudes > NGIMUMagnitudesPtr;
typedef boost::shared_ptr< ::ngimu::NGIMUMagnitudes const> NGIMUMagnitudesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ngimu::NGIMUMagnitudes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ngimu::NGIMUMagnitudes_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ngimu

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'ngimu': ['/home/awad1080/Desktop/ngimu_ws/src/ngimu/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ngimu::NGIMUMagnitudes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ngimu::NGIMUMagnitudes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ngimu::NGIMUMagnitudes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ngimu::NGIMUMagnitudes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ngimu::NGIMUMagnitudes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ngimu::NGIMUMagnitudes_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ngimu::NGIMUMagnitudes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "afa562698c740c0a2db1c9d9f6327002";
  }

  static const char* value(const ::ngimu::NGIMUMagnitudes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xafa562698c740c0aULL;
  static const uint64_t static_value2 = 0x2db1c9d9f6327002ULL;
};

template<class ContainerAllocator>
struct DataType< ::ngimu::NGIMUMagnitudes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ngimu/NGIMUMagnitudes";
  }

  static const char* value(const ::ngimu::NGIMUMagnitudes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ngimu::NGIMUMagnitudes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 mag_gyroscope\n\
float32 mag_accelerometer\n\
float32 mag_magnetometer\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::ngimu::NGIMUMagnitudes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ngimu::NGIMUMagnitudes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mag_gyroscope);
      stream.next(m.mag_accelerometer);
      stream.next(m.mag_magnetometer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NGIMUMagnitudes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ngimu::NGIMUMagnitudes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ngimu::NGIMUMagnitudes_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mag_gyroscope: ";
    Printer<float>::stream(s, indent + "  ", v.mag_gyroscope);
    s << indent << "mag_accelerometer: ";
    Printer<float>::stream(s, indent + "  ", v.mag_accelerometer);
    s << indent << "mag_magnetometer: ";
    Printer<float>::stream(s, indent + "  ", v.mag_magnetometer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NGIMU_MESSAGE_NGIMUMAGNITUDES_H
