(cl:defpackage ngimu-msg
  (:use )
  (:export
   "<NGIMUALTITUDE>"
   "NGIMUALTITUDE"
   "<NGIMUAUXSERIAL>"
   "NGIMUAUXSERIAL"
   "<NGIMUBATTERY>"
   "NGIMUBATTERY"
   "<NGIMUEARTHACCELERATION>"
   "NGIMUEARTHACCELERATION"
   "<NGIMUEULER>"
   "NGIMUEULER"
   "<NGIMUHUMIDITY>"
   "NGIMUHUMIDITY"
   "<NGIMULINEARACCELERATION>"
   "NGIMULINEARACCELERATION"
   "<NGIMUMAGNITUDES>"
   "NGIMUMAGNITUDES"
   "<NGIMUQUATERNION>"
   "NGIMUQUATERNION"
   "<NGIMUROTATIONMATRIX>"
   "NGIMUROTATIONMATRIX"
   "<NGIMUSENSORS>"
   "NGIMUSENSORS"
   "<NGIMUTEMPERATURE>"
   "NGIMUTEMPERATURE"
  ))

