# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ngimu/NGIMUSensors.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class NGIMUSensors(genpy.Message):
  _md5sum = "45f09260ad0d83cd715dfa3ebd097b05"
  _type = "ngimu/NGIMUSensors"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
float32 gyroscopeX
float32 gyroscopeY
float32 gyroscopeZ
float32 accelerometerX
float32 accelerometerY
float32 accelerometerZ
float32 magnetometerX
float32 magnetometerY
float32 magnetometerZ
float32 barometer

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','gyroscopeX','gyroscopeY','gyroscopeZ','accelerometerX','accelerometerY','accelerometerZ','magnetometerX','magnetometerY','magnetometerZ','barometer']
  _slot_types = ['std_msgs/Header','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,gyroscopeX,gyroscopeY,gyroscopeZ,accelerometerX,accelerometerY,accelerometerZ,magnetometerX,magnetometerY,magnetometerZ,barometer

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(NGIMUSensors, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.gyroscopeX is None:
        self.gyroscopeX = 0.
      if self.gyroscopeY is None:
        self.gyroscopeY = 0.
      if self.gyroscopeZ is None:
        self.gyroscopeZ = 0.
      if self.accelerometerX is None:
        self.accelerometerX = 0.
      if self.accelerometerY is None:
        self.accelerometerY = 0.
      if self.accelerometerZ is None:
        self.accelerometerZ = 0.
      if self.magnetometerX is None:
        self.magnetometerX = 0.
      if self.magnetometerY is None:
        self.magnetometerY = 0.
      if self.magnetometerZ is None:
        self.magnetometerZ = 0.
      if self.barometer is None:
        self.barometer = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.gyroscopeX = 0.
      self.gyroscopeY = 0.
      self.gyroscopeZ = 0.
      self.accelerometerX = 0.
      self.accelerometerY = 0.
      self.accelerometerZ = 0.
      self.magnetometerX = 0.
      self.magnetometerY = 0.
      self.magnetometerZ = 0.
      self.barometer = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_10f().pack(_x.gyroscopeX, _x.gyroscopeY, _x.gyroscopeZ, _x.accelerometerX, _x.accelerometerY, _x.accelerometerZ, _x.magnetometerX, _x.magnetometerY, _x.magnetometerZ, _x.barometer))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.gyroscopeX, _x.gyroscopeY, _x.gyroscopeZ, _x.accelerometerX, _x.accelerometerY, _x.accelerometerZ, _x.magnetometerX, _x.magnetometerY, _x.magnetometerZ, _x.barometer,) = _get_struct_10f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_10f().pack(_x.gyroscopeX, _x.gyroscopeY, _x.gyroscopeZ, _x.accelerometerX, _x.accelerometerY, _x.accelerometerZ, _x.magnetometerX, _x.magnetometerY, _x.magnetometerZ, _x.barometer))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.gyroscopeX, _x.gyroscopeY, _x.gyroscopeZ, _x.accelerometerX, _x.accelerometerY, _x.accelerometerZ, _x.magnetometerX, _x.magnetometerY, _x.magnetometerZ, _x.barometer,) = _get_struct_10f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_10f = None
def _get_struct_10f():
    global _struct_10f
    if _struct_10f is None:
        _struct_10f = struct.Struct("<10f")
    return _struct_10f
